apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: boompow-payments
  namespace: boompow
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: boompow
            image: replaceme
            command: ["/bin/bash", "-c"]
            args: ["python payment_processor.py --node http://pippin-banano.pippin:11338 --wallet $(WALLET_ID)"]
            env:
              - name: REDIS_HOST
                value: redis-0.redis
              - name: WALLET_ID
                valueFrom:
                  secretKeyRef:
                    name: boompow
                    key: wallet_id
          restartPolicy: OnFailure
