apiVersion: v1
kind: Service
metadata:
  name: boompow
  namespace: boompow
spec:
  type: ClusterIP
  ports:
  - port: 5035
    targetPort: 5035
    name: servicews
  - port: 5030
    targetPort: 5030
    name: service
  - port: 5031
    targetPort: 5031
    name: upcheck
  selector:
    app: boompow
